/**
 * This is a plant class that generates money
 * @author Dmytro Sytnik (VanArman)
 * @version 13 October, 2018
 *
 * @author Ahmed Romih (decarbonite)
 * @version 26 October, 2018
 */
public class MoneyPlant extends NPC {
    private int moneyToRise;

    /**
     * Initializes a new MoneyPlant
     * @param health Plant's health
     * @param money Amount of money generated by MoneyPlant
     */
    public MoneyPlant(int health, int money){
        super(health, 50,0, View.SUNFLOWER_IMAGE);
        this.moneyToRise = money;
    }

    /**
     * Method is not used
     * @param npc NPC to be attacked
     */
    @Override
    public void attack(NPC npc) {
        return;
    }

    /**
     * Return money generated by MoneyPlant
     * @return int amount of money player gain from one MoneyFlower
     */
    public int getMoney(){
        return moneyToRise;
    }
}
